### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by praisethemoon** [realbogart/smallprofiler#1]
Hello, I would like to integrate this library in my open-source project, but I would like to know its license, do you plan to add a License/Copyright file, or at least specify the license in source code?

Oh and thank you for this great tool 👍  :)

**Comment by realbogart** [comment]
Hi! Cool that you like the tool! 

Feel free to use it however you want. I will soon add a comment with the license to the source.

**Comment by praisethemoon** [comment]
You're awesome! Thank you very much! I think MIT would be fair enough :) 
Keep up the good work!
